export const SERVICES = [
  { id: 1, slug: 'general-checkup', title: 'General Checkup', icon: 'tooth',
    shortDesc: 'Comprehensive oral health exams for the whole family.',
    description: 'Our thorough dental exams include digital X-rays, gum health assessment, oral cancer screening, and a personalised treatment plan.',
    duration: '60 min', price: 'From $80' },
  { id: 2, slug: 'teeth-cleaning', title: 'Teeth Cleaning', icon: 'sparkles',
    shortDesc: 'Professional cleaning for a brighter, healthier smile.',
    description: 'Remove plaque, tartar, and stains with our professional hygiene service. Recommended every 6 months.',
    duration: '45 min', price: 'From $120' },
  { id: 3, slug: 'teeth-whitening', title: 'Teeth Whitening', icon: 'sun',
    shortDesc: 'Safe, effective whitening for a radiant smile.',
    description: 'In-office Zoom whitening or custom take-home trays — choose the option that fits your lifestyle.',
    duration: '90 min', price: 'From $350' },
  { id: 4, slug: 'dental-implants', title: 'Dental Implants', icon: 'shield',
    shortDesc: 'Permanent tooth replacement that looks and feels natural.',
    description: 'Titanium implants fused with your jawbone provide a stable, long-lasting foundation for crowns or bridges.',
    duration: 'Multi-visit', price: 'From $3,000' },
  { id: 5, slug: 'orthodontics', title: 'Orthodontics', icon: 'alignLeft',
    shortDesc: 'Braces and clear aligners for all ages.',
    description: 'Traditional metal braces, ceramic braces, and Invisalign clear aligners to give you the smile you deserve.',
    duration: '12–24 months', price: 'From $3,500' },
  { id: 6, slug: 'root-canal', title: 'Root Canal', icon: 'activity',
    shortDesc: 'Pain relief and tooth preservation in one visit.',
    description: 'Modern root canal therapy is comfortable and quick — save your tooth and eliminate infection.',
    duration: '90 min', price: 'From $700' },
  { id: 7, slug: 'cosmetic-dentistry', title: 'Cosmetic Dentistry', icon: 'star',
    shortDesc: 'Veneers, bonding, and smile makeovers.',
    description: 'Porcelain veneers, composite bonding, and full smile redesigns tailored to your facial aesthetics.',
    duration: 'Varies', price: 'From $500' },
  { id: 8, slug: 'pediatric-dentistry', title: 'Pediatric Dentistry', icon: 'heart',
    shortDesc: 'Gentle, friendly dental care for children.',
    description: 'We make first dental visits fun and stress-free, building healthy habits that last a lifetime.',
    duration: '45 min', price: 'From $60' },
];

export const TESTIMONIALS = [
  { _id: '1', name: 'Sarah M.', role: 'Patient for 4 years', rating: 5,
    text: "Dr. Tanwar is incredible. He made my root canal completely painless — I was shocked. I've been recommending Health Corner to everyone I know." },
  { _id: '2', name: 'James T.', role: 'Invisalign patient', rating: 5,
    text: "I was nervous about getting Invisalign at 38, but the results have completely changed my confidence. The process was explained clearly every step of the way." },
  { _id: '3', name: 'Maya R.', role: 'New patient', rating: 5,
    text: "Brought my daughter in for her first check-up and she actually wants to go back! The kids area is so welcoming. Genuine five-star experience." },
  { _id: '4', name: 'David K.', role: 'Implant patient', rating: 5,
    text: "After losing a tooth in an accident I was devastated. The implant looks and feels exactly like my real tooth. Exceptional work and aftercare." },
];
